### Get post by id

GET {{baseUrl}}/1
Accept: application/json

### Create new post

POST {{baseUrl}}
Accept: application/json

{"id": "2", "userId": "7", "Test title 2", "Test body 2"}

### Update some post

PUT {{baseUrl}}/2
Accept: application/json

{"id": "2", "userId": "8", "Test title 2 updated", "Test body 2 updated"}

### Delete some post

DELETE {{baseUrl}}/2
Accept: application/json

